#!/bin/sh
# Copyright (c) 2013 Philippe Charrière aka @k33g_org
#
# All rights reserved. No warranty, explicit or implicit, provided.
#

TOOLS_PATH=`dirname "$0"`

java -jar $TOOLS_PATH/golio.0.0-BETA.jar $1


